export const EVENTS = {
  CORTEX_REACTIVE_FAILURE: 'CORTEX_REACTIVE_FAILURE',
  CORTEX_AUTONOMY_FAILURE: 'CORTEX_AUTONOMY_FAILURE',
  REACTIVE_STEP_FAILED: 'REACTIVE_STEP_FAILED',
  TOOL_INTENT_UNSETTLED: 'TOOL_INTENT_UNSETTLED',
  AGENT_TRAJECTORY_UPDATE: 'AGENT_TRAJECTORY_UPDATE'
} as const;

export type TelemetryEvent = (typeof EVENTS)[keyof typeof EVENTS];
