export const EVENTS = {
  CORTEX_REACTIVE_FAILURE: 'CORTEX_REACTIVE_FAILURE',
  CORTEX_AUTONOMY_FAILURE: 'CORTEX_AUTONOMY_FAILURE',
  REACTIVE_STEP_FAILED: 'REACTIVE_STEP_FAILED'
} as const;

export type TelemetryEvent = (typeof EVENTS)[keyof typeof EVENTS];
